name: Branch Check

on: pull_request

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check target and source branches
        run: |
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "develop" ]]; then
            echo "::error::Pull requests to 'main' must originate from 'develop'."
            exit 1
          else
            echo "Check passed or PR is not targeting 'main'."
          fi
