name: Unity CI

on: [pull_request]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        
